### ISSUE TITLE
Issue with tap animation

### ISSUE THREAD

**Issue by jaredm577** [pedker/OLED-BongoCat-Revision#3]
First off thank you for your awesome code!

I am trying to implement it into a hand wired keyboard, and have pretty much dropped your code straight into my keymap, and it works except for the Tap animation. It idles correctly, but on key presses goes straight to the Prep animation frame and stays there until it goes back to the idle. I can't for the life of me figure out why this could be and would really appreciate some help. This is my first time working with QMK and really programming at all so I am hoping its a really obvious error that you might be able to help me with.

I have put my keymap here if you wouldn't mind taking a look, and a video of the problem as well. Thank you!
https://github.com/jaredm577/PicoPad-V2/blob/main/keymap.c

https://github.com/pedker/OLED-BongoCat-Revision/assets/131953412/a6f5b20d-bd39-48d3-8ae9-5ffd05b857ba

**Comment by pedker** [comment]
Hi! Unfortunately I'm not going to be able to help you completely solve your problem because I don't have the hardware you're trying to port over to. That hardware being a hand-wired build makes it even more true. Here are a few things I can think of that may help kickstart your bug hunt:

- Because they are different boards, there may be something I used that was defined differently or not at all within your firmware than the way it was for the Satisfaction75's firmware. 
- Make sure the key detection still works on your hardware. There may have been something assumed true with the Sat75 that isn't on your board, such as the matrix. I would try printing the result of detect_key_down() to your OLED and make sure it still behaves properly; for any given cycle, it should be returning true when a key is newly pressed down.
- Make sure the anim_states are still behaving correctly. You can print the current state to your OLED and check. 

I will be closing this issue with this comment, since this problem doesn't affect this repo. Good luck and Happy New Year!
